version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Moscow
  labels:
    - "testing1"
- package-ecosystem: maven
  directory: "/kafka-ui-e2e-checks"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Moscow
  labels:
    - "testing2"
